### ISSUE TITLE
USING THE PROJECT

### ISSUE THREAD

**Issue by absingh31** [TeamHG-Memex/deep-deep#18]
@kmike  Can the readme file be made more descriptive, because it's difficult to set the project up and use it for students like us!

**Comment by absingh31** [comment]
If possible give us a usecase

**Comment by lopuhin** [comment]
Hello @absingh31 , this is a crawler that learns which links to follow using reinforcement learning. You can use it if you can define a function that returns reward given crawled page (e.g. a binary page classifier) - and the crawler will learn to maximize cumulative reward.
 Do you have any specific questions or difficulties?

**Comment by absingh31** [comment]
Hi @lopuhin , sorry for these simple questions but in which file should I define the reward function? And I even have some on dependencies between the scripts.

**Comment by absingh31** [comment]
@lopuhin I want to crawl .onion sites. Just wanted to know the steps.

**Comment by lopuhin** [comment]
@absingh31 this project is not an onion crawler, despite it's deep-deep name. From the README:
> Deep-Deep is a Scrapy-based crawler which uses Reinforcement Learning methods to learn which links to follow.
> It is called Deep-Deep, but it doesn't use Deep Learning, and it is not only for Deep web. Weird.

It can crawl onion sites (like most scrapy spiders) if you set up a tor proxy, but this is out of scope of this project.

**Comment by absingh31** [comment]
@lopuhin  thanks for info.
