### ISSUE TITLE
 No such file or directory: 'Q.joblib'

### ISSUE THREAD

**Issue by Nitin-Panwar** [TeamHG-Memex/deep-deep#25]
I am getting below error while running the standalone.py. Could you please help me understand why is it coming. 
command :- scrapy runspider ../examples/standalone.py -a url=http://example.com -a q_model=Q.joblib

![image](https://user-images.githubusercontent.com/19501617/36245819-f5379fa8-1252-11e8-91ff-72d21490ba68.png)

**Comment by lopuhin** [comment]
@Nitin-Panwar this example assumes that you already have ``Q.joblib`` file from normal deepdeep run - it's called "standalone" in a sense that it's standalone from deep-deep.

**Comment by Nitin-Panwar** [comment]
Could you please let me know how to generate my Q.joblib file for the first time, is there any file that i could run. Any help will be really appreciated. 
If you could let me know step by step process to start relevancy  crawler, i am not able to mimic it from the doc available.

**Comment by lopuhin** [comment]
Several cases are described in the section "Running" in README: https://github.com/TeamHG-Memex/deep-deep#running
